import { createClient } from '@supabase/supabase-js'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SECRET_KEY
)

export async function GET(request, { params }) {
  const { data: log, error } = await supabase
    .from('pour_logs')
    .select('*')
    .eq('id', params.id)
    .single()

  if (error || !log) {
    return new Response('Pour log not found', { status: 404 })
  }

  const { data: foundations } = await supabase
    .from('pour_log_foundations')
    .select('*')
    .eq('pour_log_id', log.id)

  const { data: trucks } = await supabase
    .from('pour_log_trucks')
    .select('*')
    .eq('pour_log_id', log.id)
    .order('truck_number', { ascending: true })

  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([612, 792])
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const { height } = page.getSize()

  // Header
  page.drawRectangle({ x: 0, y: height - 80, width: 612, height: 80, color: rgb(0.1, 0.1, 0.1) })
  page.drawText('DRILLED SHAFT POUR LOG', { x: 40, y: height - 45, size: 20, font: boldFont, color: rgb(1, 1, 1) })
  page.drawText('Ironclad Construction LLC', { x: 40, y: height - 65, size: 11, font, color: rgb(0.8, 0.8, 0.8) })

  let y = height - 100

  const drawField = (label, value, x, yPos, width) => {
    page.drawText(label, { x, y: yPos, size: 8, font: boldFont, color: rgb(0.5, 0.5, 0.5) })
    page.drawText(String(value || '-'), { x, y: yPos - 14, size: 10, font, color: rgb(0.1, 0.1, 0.1) })
    return yPos - 30
  }

  const drawLine = (yPos) => {
    page.drawLine({ start: { x: 40, y: yPos }, end: { x: 572, y: yPos }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) })
  }

  const drawSectionHeader = (text, yPos) => {
    page.drawRectangle({ x: 40, y: yPos - 4, width: 532, height: 18, color: rgb(0.95, 0.95, 0.95) })
    page.drawText(text, { x: 44, y: yPos, size: 10, font: boldFont, color: rgb(0.2, 0.2, 0.2) })
    return yPos - 24
  }

  // Job Info
  y = drawSectionHeader('JOB INFO', y)
  y = drawField('PROJECT', log.project_name, 40, y, 200)
  const y2 = drawField('DATE', log.log_date, 220, y + 30, 150)
  y = Math.min(y, y2)
  y = drawField('WEATHER', log.weather, 40, y, 150)
  const y3 = drawField('AMBIENT TEMP', log.ambient_temp, 220, y + 30, 150)
  y = Math.min(y, y3)
  y = drawField('SUPPLIER', log.concrete_supplier, 40, y, 200)
  const y4 = drawField('SUBMITTED BY', log.submitted_by, 220, y + 30, 150)
  y = Math.min(y, y4)
  y -= 10
  drawLine(y)
  y -= 15

  // Foundations
  if (foundations && foundations.length > 0) {
    y = drawSectionHeader('FOUNDATIONS POURED', y)
    for (const f of foundations) {
      if (y < 100) break
      page.drawText(f.foundation_id || '-', { x: 40, y, size: 11, font: boldFont, color: rgb(0.1, 0.1, 0.1) })
      y -= 16
      page.drawText('Depth: ' + (f.total_depth || '-') + '   Est. Yards: ' + (f.estimated_yards || '-'), { x: 44, y, size: 9, font, color: rgb(0.4, 0.4, 0.4) })
      y -= 14
      if (f.notes) {
        page.drawText('Notes: ' + f.notes, { x: 44, y, size: 9, font, color: rgb(0.4, 0.4, 0.4) })
        y -= 14
      }
      y -= 6
    }
    drawLine(y)
    y -= 15
  }

  // Trucks
  if (trucks && trucks.length > 0) {
    y = drawSectionHeader('CONCRETE TRUCKS', y)
    for (const t of trucks) {
      if (y < 120) {
        const newPage = pdfDoc.addPage([612, 792])
        y = 750
      }
      page.drawText('TRUCK ' + t.truck_number, { x: 40, y, size: 11, font: boldFont, color: rgb(0.1, 0.1, 0.1) })
      y -= 16
      const timeStr = 'Arrival: ' + (t.arrival_time || '-') + '   Start: ' + (t.pour_start || '-') + '   Complete: ' + (t.pour_complete || '-')
      page.drawText(timeStr, { x: 44, y, size: 9, font, color: rgb(0.3, 0.3, 0.3) })
      y -= 14
      const mixStr = 'Yards: ' + (t.yards || '-') + '   Temp: ' + (t.concrete_temp || '-') + '   Slump: ' + (t.slump || '-') + '   Air: ' + (t.air_content || '-')
      page.drawText(mixStr, { x: 44, y, size: 9, font, color: rgb(0.3, 0.3, 0.3) })
      y -= 14
      const extraStr = 'Water Added: ' + (t.water_added || '-') + '   Cylinders: ' + (t.cylinders_cast || '-') + '   Depth Reading: ' + (t.depth_reading || '-')
      page.drawText(extraStr, { x: 44, y, size: 9, font, color: rgb(0.3, 0.3, 0.3) })
      y -= 14
      if (t.foundations_served) {
        page.drawText('Foundations Served: ' + t.foundations_served, { x: 44, y, size: 9, font, color: rgb(0.3, 0.3, 0.3) })
        y -= 14
      }
      if (t.notes) {
        page.drawText('Notes: ' + t.notes, { x: 44, y, size: 9, font, color: rgb(0.3, 0.3, 0.3) })
        y -= 14
      }
      y -= 8
      drawLine(y)
      y -= 12
    }
  }

  // Footer
  page.drawText('Generated by Ironclad Reports - ' + new Date().toLocaleDateString(), {
    x: 40, y: 25, size: 8, font, color: rgb(0.6, 0.6, 0.6)
  })

  const pdfBytes = await pdfDoc.save()

  return new Response(pdfBytes, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="pour-log-' + log.project_name + '-' + log.log_date + '.pdf"'
    }
  })
}
