import { createClient } from '@supabase/supabase-js'
import { Resend } from 'resend'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SECRET_KEY
)

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request) {
  try {
    const formData = await request.formData()

    const project_name = formData.get('project_name')
    const report_date = formData.get('report_date')
    const crew_count = parseInt(formData.get('crew_count'))
    const work_completed = formData.get('work_completed')
    const equipment_used = formData.get('equipment_used')
    const safety_issues = formData.get('safety_issues')
    const weather = formData.get('weather')
    const submitted_by = formData.get('submitted_by')

    // Save to Supabase
    const { error: dbError } = await supabase
      .from('reports')
      .insert({
        project_name,
        report_date,
        crew_count,
        work_completed,
        equipment_used,
        safety_issues,
        weather,
        submitted_by
      })

    if (dbError) throw dbError

    // Generate PDF
    const pdfDoc = await PDFDocument.create()
    const page = pdfDoc.addPage([612, 792])
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

    const { height } = page.getSize()
    let y = height - 50

    // Header
    page.drawRectangle({
      x: 0,
      y: height - 80,
      width: 612,
      height: 80,
      color: rgb(0.8, 0.2, 0)
    })

    page.drawText('IRONCLAD DAILY REPORT', {
      x: 40,
      y: height - 45,
      size: 22,
      font: boldFont,
      color: rgb(1, 1, 1)
    })

    page.drawText('Ironclad Construction LLC', {
      x: 40,
      y: height - 65,
      size: 11,
      font,
      color: rgb(1, 1, 1)
    })

    y = height - 110

    // Field helper
    const drawField = (label, value, yPos) => {
      page.drawText(label, {
        x: 40,
        y: yPos,
        size: 10,
        font: boldFont,
        color: rgb(0.4, 0.4, 0.4)
      })
      page.drawText(String(value || '—'), {
        x: 40,
        y: yPos - 18,
        size: 12,
        font,
        color: rgb(0.1, 0.1, 0.1)
      })
      page.drawLine({
        start: { x: 40, y: yPos - 28 },
        end: { x: 572, y: yPos - 28 },
        thickness: 0.5,
        color: rgb(0.85, 0.85, 0.85)
      })
      return yPos - 50
    }

    // Draw long text field
    const drawLongField = (label, value, yPos) => {
      page.drawText(label, {
        x: 40,
        y: yPos,
        size: 10,
        font: boldFont,
        color: rgb(0.4, 0.4, 0.4)
      })
      const words = String(value || '—').split(' ')
      let line = ''
      let lineY = yPos - 18
      for (const word of words) {
        const test = line + word + ' '
        if (test.length > 72) {
          page.drawText(line.trim(), { x: 40, y: lineY, size: 12, font, color: rgb(0.1, 0.1, 0.1) })
          lineY -= 16
          line = word + ' '
        } else {
          line = test
        }
      }
      if (line.trim()) {
        page.drawText(line.trim(), { x: 40, y: lineY, size: 12, font, color: rgb(0.1, 0.1, 0.1) })
        lineY -= 16
      }
      page.drawLine({
        start: { x: 40, y: lineY - 6 },
        end: { x: 572, y: lineY - 6 },
        thickness: 0.5,
        color: rgb(0.85, 0.85, 0.85)
      })
      return lineY - 26
    }

    y = drawField('PROJECT NAME', project_name, y)
    y = drawField('REPORT DATE', report_date, y)
    y = drawField('SUBMITTED BY', submitted_by, y)
    y = drawField('CREW COUNT ON SITE', crew_count, y)
    y = drawField('WEATHER CONDITIONS', weather, y)
    y = drawLongField('WORK COMPLETED TODAY', work_completed, y)
    y = drawField('EQUIPMENT USED', equipment_used, y)
    y = drawLongField('SAFETY / ISSUES', safety_issues, y)

    // Footer
    page.drawText(`Generated by Ironclad Reports — ${new Date().toLocaleDateString()}`, {
      x: 40,
      y: 30,
      size: 9,
      font,
      color: rgb(0.6, 0.6, 0.6)
    })

    const pdfBytes = await pdfDoc.save()
    const pdfBuffer = Buffer.from(pdfBytes)

    // Send email
    await resend.emails.send({
      from: 'Ironclad Reports <onboarding@resend.dev>',
      to: process.env.REPORT_DELIVERY_EMAIL,
      subject: `Daily Report — ${project_name} — ${report_date}`,
      html: `
        <h2>Ironclad Daily Report</h2>
        <p><strong>Project:</strong> ${project_name}</p>
        <p><strong>Date:</strong> ${report_date}</p>
        <p><strong>Submitted By:</strong> ${submitted_by}</p>
        <p><strong>Crew Count:</strong> ${crew_count}</p>
        <p><strong>Weather:</strong> ${weather}</p>
        <p><strong>Work Completed:</strong> ${work_completed}</p>
        <p><strong>Equipment Used:</strong> ${equipment_used}</p>
        <p><strong>Safety / Issues:</strong> ${safety_issues}</p>
        <p style="color:#999; font-size:12px;">PDF attached.</p>
      `,
      attachments: [
        {
          filename: `ironclad-report-${project_name}-${report_date}.pdf`,
          content: pdfBuffer
        }
      ]
    })

    // Redirect to success page
    return Response.redirect(new URL('/success', request.url))

  } catch (err) {
    console.error(err)
    return new Response('Something went wrong. Please try again.', { status: 500 })
  }
}
