import { createClient } from '@supabase/supabase-js'
import { Resend } from 'resend'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SECRET_KEY
)

const resend = new Resend(process.env.RESEND_API_KEY)

export async function GET(request, { params }) {
  const { data: report, error } = await supabase
    .from('reports')
    .select('*')
    .eq('id', params.id)
    .single()

  if (error || !report) {
    return new Response('Report not found', { status: 404 })
  }

  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([612, 792])
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const { height } = page.getSize()

  page.drawRectangle({
    x: 0,
    y: height - 80,
    width: 612,
    height: 80,
    color: rgb(0.8, 0.2, 0)
  })

  page.drawText('IRONCLAD DAILY REPORT', {
    x: 40,
    y: height - 45,
    size: 22,
    font: boldFont,
    color: rgb(1, 1, 1)
  })

  page.drawText('Ironclad Construction LLC', {
    x: 40,
    y: height - 65,
    size: 11,
    font,
    color: rgb(1, 1, 1)
  })

  let y = height - 110

  const drawField = (label, value, yPos) => {
    page.drawText(label, {
      x: 40,
      y: yPos,
      size: 10,
      font: boldFont,
      color: rgb(0.4, 0.4, 0.4)
    })
    page.drawText(String(value || '—'), {
      x: 40,
      y: yPos - 18,
      size: 12,
      font,
      color: rgb(0.1, 0.1, 0.1)
    })
    page.drawLine({
      start: { x: 40, y: yPos - 28 },
      end: { x: 572, y: yPos - 28 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85)
    })
    return yPos - 50
  }

  const drawLongField = (label, value, yPos) => {
    page.drawText(label, {
      x: 40,
      y: yPos,
      size: 10,
      font: boldFont,
      color: rgb(0.4, 0.4, 0.4)
    })
    const words = String(value || '—').split(' ')
    let line = ''
    let lineY = yPos - 18
    for (const word of words) {
      const test = line + word + ' '
      if (test.length > 72) {
        page.drawText(line.trim(), { x: 40, y: lineY, size: 12, font, color: rgb(0.1, 0.1, 0.1) })
        lineY -= 16
        line = word + ' '
      } else {
        line = test
      }
    }
    if (line.trim()) {
      page.drawText(line.trim(), { x: 40, y: lineY, size: 12, font, color: rgb(0.1, 0.1, 0.1) })
      lineY -= 16
    }
    page.drawLine({
      start: { x: 40, y: lineY - 6 },
      end: { x: 572, y: lineY - 6 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85)
    })
    return lineY - 26
  }

  y = drawField('PROJECT NAME', report.project_name, y)
  y = drawField('REPORT DATE', report.report_date, y)
  y = drawField('SUBMITTED BY', report.submitted_by, y)
  y = drawField('CREW COUNT ON SITE', report.crew_count, y)
  y = drawField('WEATHER CONDITIONS', report.weather, y)
  y = drawLongField('WORK COMPLETED TODAY', report.work_completed, y)
  y = drawField('EQUIPMENT USED', report.equipment_used, y)
  y = drawLongField('SAFETY / ISSUES', report.safety_issues, y)

  page.drawText(`Generated by Ironclad Reports — ${new Date().toLocaleDateString()}`, {
    x: 40,
    y: 30,
    size: 9,
    font,
    color: rgb(0.6, 0.6, 0.6)
  })

  const pdfBytes = await pdfDoc.save()
  const pdfBuffer = Buffer.from(pdfBytes)

  await resend.emails.send({
    from: 'Ironclad Reports <onboarding@resend.dev>',
    to: process.env.REPORT_DELIVERY_EMAIL,
    subject: `Daily Report — ${report.project_name} — ${report.report_date}`,
    html: `
      <h2>Ironclad Daily Report</h2>
      <p><strong>Project:</strong> ${report.project_name}</p>
      <p><strong>Date:</strong> ${report.report_date}</p>
      <p><strong>Submitted By:</strong> ${report.submitted_by}</p>
      <p><strong>Crew Count:</strong> ${report.crew_count}</p>
      <p><strong>Weather:</strong> ${report.weather}</p>
      <p><strong>Work Completed:</strong> ${report.work_completed}</p>
      <p><strong>Equipment Used:</strong> ${report.equipment_used}</p>
      <p><strong>Safety / Issues:</strong> ${report.safety_issues}</p>
      <p style="color:#999; font-size:12px;">PDF attached.</p>
    `,
    attachments: [
      {
        filename: `ironclad-report-${report.project_name}-${report.report_date}.pdf`,
        content: pdfBuffer
      }
    ]
  })

  return Response.redirect(new URL(`/reports/${report.id}?emailed=true`, request.url))
}
