import { createClient } from '@supabase/supabase-js'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SECRET_KEY
)

export async function GET(request, { params }) {
  const { data: report, error } = await supabase
    .from('reports')
    .select('*')
    .eq('id', params.id)
    .single()

  if (error || !report) {
    return new Response('Report not found', { status: 404 })
  }

  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([612, 792])
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const { height } = page.getSize()

  page.drawRectangle({
    x: 0,
    y: height - 80,
    width: 612,
    height: 80,
    color: rgb(0.8, 0.2, 0)
  })

  page.drawText('IRONCLAD DAILY REPORT', {
    x: 40,
    y: height - 45,
    size: 22,
    font: boldFont,
    color: rgb(1, 1, 1)
  })

  page.drawText('Ironclad Construction LLC', {
    x: 40,
    y: height - 65,
    size: 11,
    font,
    color: rgb(1, 1, 1)
  })

  let y = height - 110

  const drawField = (label, value, yPos) => {
    page.drawText(label, {
      x: 40,
      y: yPos,
      size: 10,
      font: boldFont,
      color: rgb(0.4, 0.4, 0.4)
    })
    page.drawText(String(value || '—'), {
      x: 40,
      y: yPos - 18,
      size: 12,
      font,
      color: rgb(0.1, 0.1, 0.1)
    })
    page.drawLine({
      start: { x: 40, y: yPos - 28 },
      end: { x: 572, y: yPos - 28 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85)
    })
    return yPos - 50
  }

  const drawLongField = (label, value, yPos) => {
    page.drawText(label, {
      x: 40,
      y: yPos,
      size: 10,
      font: boldFont,
      color: rgb(0.4, 0.4, 0.4)
    })
    const words = String(value || '—').split(' ')
    let line = ''
    let lineY = yPos - 18
    for (const word of words) {
      const test = line + word + ' '
      if (test.length > 72) {
        page.drawText(line.trim(), { x: 40, y: lineY, size: 12, font, color: rgb(0.1, 0.1, 0.1) })
        lineY -= 16
        line = word + ' '
      } else {
        line = test
      }
    }
    if (line.trim()) {
      page.drawText(line.trim(), { x: 40, y: lineY, size: 12, font, color: rgb(0.1, 0.1, 0.1) })
      lineY -= 16
    }
    page.drawLine({
      start: { x: 40, y: lineY - 6 },
      end: { x: 572, y: lineY - 6 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85)
    })
    return lineY - 26
  }

  y = drawField('PROJECT NAME', report.project_name, y)
  y = drawField('REPORT DATE', report.report_date, y)
  y = drawField('SUBMITTED BY', report.submitted_by, y)
  y = drawField('CREW COUNT ON SITE', report.crew_count, y)
  y = drawField('WEATHER CONDITIONS', report.weather, y)
  y = drawLongField('WORK COMPLETED TODAY', report.work_completed, y)
  y = drawField('EQUIPMENT USED', report.equipment_used, y)
  y = drawLongField('SAFETY / ISSUES', report.safety_issues, y)

  page.drawText(`Generated by Ironclad Reports — ${new Date().toLocaleDateString()}`, {
    x: 40,
    y: 30,
    size: 9,
    font,
    color: rgb(0.6, 0.6, 0.6)
  })

  const pdfBytes = await pdfDoc.save()

  return new Response(pdfBytes, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="ironclad-report-${report.project_name}-${report.report_date}.pdf"`
    }
  })
}
